# Generated by Django 3.2.12 on 2022-03-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freekey11', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
