# Generated by Django 3.2.12 on 2022-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freekey11', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(default='type query here.....', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ImgView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('img_uplaod', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=140)),
                ('Message', models.TextField(default='type query here.....', max_length=500)),
            ],
        ),
    ]
